# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:10.10.0

before_script:
- npm install

stages:
  - lint
  - test

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

lint:
  stage: lint
  script:
    - npm run lint

test:
  stage: test
  script:
  - npm run test


